#! /usr/bin/env python3
codes = '''PGA
PGB
PGC
PGD
PGE
PGF
PGG
PGH
PGI
PGK
PGL
PGM
PGN
PGO
PGP
PGR
PGS
PGU
PGV
PGX
PGZ
PHA
PHB
PHC
PHD
PHE
PHF
PHG
PHH
PHI
PHJ
PHK
PHL
PHN
PHO
PHP
PHR
PHS
PHT
PHU
PHW
PHX
PHY
PHZ'''

for code in codes.splitlines():
  if (len(code.strip()) > 0):
    print("'" + code + "', ", end='')
print()
